### ISSUE TITLE
Add links for each event in event section 

### ISSUE THREAD

**Issue by Deepak91168** [istenith/istenith.github.io#135]
![Screenshot from 2022-10-20 21-43-23](https://user-images.githubusercontent.com/78257493/197002531-743abd50-62c6-4659-a161-00f135194c40.png)

Create button on bottom right corner of the div and provide appropriate padding, check for responsiveness as well :)

**Comment by CodeRyliCode** [comment]
Hi , could I have this assigned to me? I also wanted to ask what the button is supposed to do regarding responsiveness? When the button is clicked, what is supposed to happen?

**Comment by harsh0620** [comment]
Hey @Deepak91168 Please assign me this task.
