### ISSUE TITLE
Update the footer 

### ISSUE THREAD

**Issue by AceHunterr** [istenith/istenith.github.io#156]
**Issue Description**
Currently the footer is not looking very nice

---

**Describe the solution you'd like**
Update the footer by minimizing it , remove extra spaces and avoid unnecessary information

---

**How to reproduce the bug**
run your server by 
"npm install" ,followed by 
"npm start"

Go to the url "localhost:3000/#/"

**Comment by ayan-choradia** [comment]
ayan-choradia
