### ISSUE TITLE
Adding tags in the Gallery Page

### ISSUE THREAD

**Issue by AceHunterr** [istenith/istenith.github.io#157]
**Issue Description**
Currently there is a mouse click effect on the images of the gallery page which is not required and category text missing.

---

**Describe the solution you'd like**
Categorize the images in the gallery put text tag in each image in the gallery on the bottom left corner or top left. Also remove the mouseClick effect.

---

**How to reproduce the bug**
run your server by 
"npm install" ,followed by 
"npm start"

Go to the url "localhost:3000/#/gallery"
or just navigate through navbar.

**Comment by git-ankuryadav** [comment]
git-ankuryadav
