### ISSUE TITLE
Better rewording suggestion

### ISSUE THREAD

**Issue by avinal** [istenith/istenith.github.io#62]
Nothing bad though, but the word *Orgi* does not seem to be a nice abbreviation for *Organization*. Also, it does not help to redirect the thinking of an average college guy once he is fixed on some totally different meaning.  So either *Org* or *Organization* would be a better choice 👍🏼 

![image](https://user-images.githubusercontent.com/74113200/103135857-88b3c200-46e1-11eb-8820-fb3a382fdd37.png)

**Comment by Sov-trotter** [comment]
We'll look into it. Thanks for pointing out!
