### ISSUE TITLE
Fix wierd sizing issues with the carousel

### ISSUE THREAD

**Issue by ParthPant** [istenith/istenith.github.io#90]
![image](https://user-images.githubusercontent.com/30381591/135714493-431bdb20-2de4-46cb-9ebc-cc7b31e9cc4d.png)

fix the carousel; maybe remove it and comeup with a better solution

**Comment by harsh0620** [comment]
Hey @ParthPant Please assign me this task.

**Comment by swastkk** [comment]
Closing this since, website has been Refurbished.
